#include "cym/ogl/ogl.hpp"

#if defined(__APPLE__)
#include <dlfcn.h>
static void* aplGLGetProcAddress (const char *name) {
  static void* image = NULL;
  
  if (NULL == image)
    image = dlopen("/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL", RTLD_LAZY);

  return (image ? dlsym(image, name) : NULL);
}
#endif /* __APPLE__ */

#if defined(__sgi) || defined (__sun)
#include <dlfcn.h>
#include <stdio.h>
static void* sunGetProcAddress (const GLubyte* name) {
  static void* h = NULL;
  static void* gpa;

  if (h == NULL)
  {
    if ((h = dlopen(NULL, RTLD_LAZY | RTLD_LOCAL)) == NULL) return NULL;
    gpa = dlsym(h, "glXGetProcAddress");
  }

  if (gpa != NULL)
    return ((void*(*)(const GLubyte*))gpa)(name);
  else
    return dlsym(h, (const char*)name);
}
#endif /* __sgi || __sun */

#if defined(_WIN32)

#ifdef _MSC_VER
#pragma warning(disable: 4055)
#pragma warning(disable: 4054)
#pragma warning(disable: 4996)
#endif

static int testPointer(const PROC pTest) {
  ptrdiff_t iTest;
  if(!pTest) return 0;
  iTest = (ptrdiff_t)pTest;
  
  if(iTest == 1 || iTest == 2 || iTest == 3 || iTest == -1) return 0;
  
  return 1;
}

static PROC winGetProcAddress(const char *name) {
  static HMODULE hModule = NULL; 
  if (hModule == NULL) {
    PROC pFunc = wglGetProcAddress((LPCSTR)name);
    if(testPointer(pFunc)) { return pFunc; }
    hModule = ::GetModuleHandleA("OpenGL32.dll");
  }
  return (PROC)::GetProcAddress(hModule,(LPCSTR)name);
}
  
#define glGetProcAddress(name) winGetProcAddress(name)
#else
#if defined(__APPLE__)
  #define glGetProcAddress(name) aplGLGetProcAddress(name)
#else
  #if defined(__sgi) || defined(__sun)
    #define glGetProcAddress(name) sunGetProcAddress(name)
  #else /* GLX */
      #include <GL/glx.h>

    #define glGetProcAddress(name) (*glXGetProcAddressARB)((const GLubyte*)name)
  #endif
#endif
#endif

PFNGLACTIVESHADERPROGRAMPROC _ptrc_glActiveShaderProgram = NULL;
PFNGLACTIVETEXTUREPROC _ptrc_glActiveTexture = NULL;
PFNGLATTACHSHADERPROC _ptrc_glAttachShader = NULL;
PFNGLBEGINCONDITIONALRENDERPROC _ptrc_glBeginConditionalRender = NULL;
PFNGLBEGINQUERYPROC _ptrc_glBeginQuery = NULL;
PFNGLBEGINQUERYINDEXEDPROC _ptrc_glBeginQueryIndexed = NULL;
PFNGLBEGINTRANSFORMFEEDBACKPROC _ptrc_glBeginTransformFeedback = NULL;
PFNGLBINDATTRIBLOCATIONPROC _ptrc_glBindAttribLocation = NULL;
PFNGLBINDBUFFERPROC _ptrc_glBindBuffer = NULL;
PFNGLBINDBUFFERBASEPROC _ptrc_glBindBufferBase = NULL;
PFNGLBINDBUFFERRANGEPROC _ptrc_glBindBufferRange = NULL;
PFNGLBINDBUFFERSBASEPROC _ptrc_glBindBuffersBase = NULL;
PFNGLBINDBUFFERSRANGEPROC _ptrc_glBindBuffersRange = NULL;
PFNGLBINDFRAGDATALOCATIONPROC _ptrc_glBindFragDataLocation = NULL;
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC _ptrc_glBindFragDataLocationIndexed = NULL;
PFNGLBINDFRAMEBUFFERPROC _ptrc_glBindFramebuffer = NULL;
PFNGLBINDIMAGETEXTUREPROC _ptrc_glBindImageTexture = NULL;
PFNGLBINDIMAGETEXTURESPROC _ptrc_glBindImageTextures = NULL;
PFNGLBINDPROGRAMPIPELINEPROC _ptrc_glBindProgramPipeline = NULL;
PFNGLBINDRENDERBUFFERPROC _ptrc_glBindRenderbuffer = NULL;
PFNGLBINDSAMPLERPROC _ptrc_glBindSampler = NULL;
PFNGLBINDSAMPLERSPROC _ptrc_glBindSamplers = NULL;
PFNGLBINDTEXTUREPROC _ptrc_glBindTexture = NULL;
PFNGLBINDTEXTUREUNITPROC _ptrc_glBindTextureUnit = NULL;
PFNGLBINDTEXTURESPROC _ptrc_glBindTextures = NULL;
PFNGLBINDTRANSFORMFEEDBACKPROC _ptrc_glBindTransformFeedback = NULL;
PFNGLBINDVERTEXARRAYPROC _ptrc_glBindVertexArray = NULL;
PFNGLBINDVERTEXBUFFERPROC _ptrc_glBindVertexBuffer = NULL;
PFNGLBINDVERTEXBUFFERSPROC _ptrc_glBindVertexBuffers = NULL;
PFNGLBLENDCOLORPROC _ptrc_glBlendColor = NULL;
PFNGLBLENDEQUATIONPROC _ptrc_glBlendEquation = NULL;
PFNGLBLENDEQUATIONSEPARATEPROC _ptrc_glBlendEquationSeparate = NULL;
PFNGLBLENDEQUATIONSEPARATEIPROC _ptrc_glBlendEquationSeparatei = NULL;
PFNGLBLENDEQUATIONIPROC _ptrc_glBlendEquationi = NULL;
PFNGLBLENDFUNCPROC _ptrc_glBlendFunc = NULL;
PFNGLBLENDFUNCSEPARATEPROC _ptrc_glBlendFuncSeparate = NULL;
PFNGLBLENDFUNCSEPARATEIPROC _ptrc_glBlendFuncSeparatei = NULL;
PFNGLBLENDFUNCIPROC _ptrc_glBlendFunci = NULL;
PFNGLBLITFRAMEBUFFERPROC _ptrc_glBlitFramebuffer = NULL;
PFNGLBLITNAMEDFRAMEBUFFERPROC _ptrc_glBlitNamedFramebuffer = NULL;
PFNGLBUFFERDATAPROC _ptrc_glBufferData = NULL;
PFNGLBUFFERSTORAGEPROC _ptrc_glBufferStorage = NULL;
PFNGLBUFFERSUBDATAPROC _ptrc_glBufferSubData = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC _ptrc_glCheckFramebufferStatus = NULL;
PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC _ptrc_glCheckNamedFramebufferStatus = NULL;
PFNGLCLAMPCOLORPROC _ptrc_glClampColor = NULL;
PFNGLCLEARPROC _ptrc_glClear = NULL;
PFNGLCLEARBUFFERDATAPROC _ptrc_glClearBufferData = NULL;
PFNGLCLEARBUFFERSUBDATAPROC _ptrc_glClearBufferSubData = NULL;
PFNGLCLEARBUFFERFIPROC _ptrc_glClearBufferfi = NULL;
PFNGLCLEARBUFFERFVPROC _ptrc_glClearBufferfv = NULL;
PFNGLCLEARBUFFERIVPROC _ptrc_glClearBufferiv = NULL;
PFNGLCLEARBUFFERUIVPROC _ptrc_glClearBufferuiv = NULL;
PFNGLCLEARCOLORPROC _ptrc_glClearColor = NULL;
PFNGLCLEARDEPTHPROC _ptrc_glClearDepth = NULL;
PFNGLCLEARDEPTHFPROC _ptrc_glClearDepthf = NULL;
PFNGLCLEARNAMEDBUFFERDATAPROC _ptrc_glClearNamedBufferData = NULL;
PFNGLCLEARNAMEDBUFFERSUBDATAPROC _ptrc_glClearNamedBufferSubData = NULL;
PFNGLCLEARNAMEDFRAMEBUFFERFIPROC _ptrc_glClearNamedFramebufferfi = NULL;
PFNGLCLEARNAMEDFRAMEBUFFERFVPROC _ptrc_glClearNamedFramebufferfv = NULL;
PFNGLCLEARNAMEDFRAMEBUFFERIVPROC _ptrc_glClearNamedFramebufferiv = NULL;
PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC _ptrc_glClearNamedFramebufferuiv = NULL;
PFNGLCLEARSTENCILPROC _ptrc_glClearStencil = NULL;
PFNGLCLEARTEXIMAGEPROC _ptrc_glClearTexImage = NULL;
PFNGLCLEARTEXSUBIMAGEPROC _ptrc_glClearTexSubImage = NULL;
PFNGLCLIENTWAITSYNCPROC _ptrc_glClientWaitSync = NULL;
PFNGLCLIPCONTROLPROC _ptrc_glClipControl = NULL;
PFNGLCOLORMASKPROC _ptrc_glColorMask = NULL;
PFNGLCOLORMASKIPROC _ptrc_glColorMaski = NULL;
PFNGLCOLORP3UIPROC _ptrc_glColorP3ui = NULL;
PFNGLCOLORP3UIVPROC _ptrc_glColorP3uiv = NULL;
PFNGLCOLORP4UIPROC _ptrc_glColorP4ui = NULL;
PFNGLCOLORP4UIVPROC _ptrc_glColorP4uiv = NULL;
PFNGLCOMPILESHADERPROC _ptrc_glCompileShader = NULL;
PFNGLCOMPRESSEDTEXIMAGE1DPROC _ptrc_glCompressedTexImage1D = NULL;
PFNGLCOMPRESSEDTEXIMAGE2DPROC _ptrc_glCompressedTexImage2D = NULL;
PFNGLCOMPRESSEDTEXIMAGE3DPROC _ptrc_glCompressedTexImage3D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC _ptrc_glCompressedTexSubImage1D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC _ptrc_glCompressedTexSubImage2D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC _ptrc_glCompressedTexSubImage3D = NULL;
PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC _ptrc_glCompressedTextureSubImage1D = NULL;
PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC _ptrc_glCompressedTextureSubImage2D = NULL;
PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC _ptrc_glCompressedTextureSubImage3D = NULL;
PFNGLCOPYBUFFERSUBDATAPROC _ptrc_glCopyBufferSubData = NULL;
PFNGLCOPYIMAGESUBDATAPROC _ptrc_glCopyImageSubData = NULL;
PFNGLCOPYNAMEDBUFFERSUBDATAPROC _ptrc_glCopyNamedBufferSubData = NULL;
PFNGLCOPYTEXIMAGE1DPROC _ptrc_glCopyTexImage1D = NULL;
PFNGLCOPYTEXIMAGE2DPROC _ptrc_glCopyTexImage2D = NULL;
PFNGLCOPYTEXSUBIMAGE1DPROC _ptrc_glCopyTexSubImage1D = NULL;
PFNGLCOPYTEXSUBIMAGE2DPROC _ptrc_glCopyTexSubImage2D = NULL;
PFNGLCOPYTEXSUBIMAGE3DPROC _ptrc_glCopyTexSubImage3D = NULL;
PFNGLCOPYTEXTURESUBIMAGE1DPROC _ptrc_glCopyTextureSubImage1D = NULL;
PFNGLCOPYTEXTURESUBIMAGE2DPROC _ptrc_glCopyTextureSubImage2D = NULL;
PFNGLCOPYTEXTURESUBIMAGE3DPROC _ptrc_glCopyTextureSubImage3D = NULL;
PFNGLCREATEBUFFERSPROC _ptrc_glCreateBuffers = NULL;
PFNGLCREATEFRAMEBUFFERSPROC _ptrc_glCreateFramebuffers = NULL;
PFNGLCREATEPROGRAMPROC _ptrc_glCreateProgram = NULL;
PFNGLCREATEPROGRAMPIPELINESPROC _ptrc_glCreateProgramPipelines = NULL;
PFNGLCREATEQUERIESPROC _ptrc_glCreateQueries = NULL;
PFNGLCREATERENDERBUFFERSPROC _ptrc_glCreateRenderbuffers = NULL;
PFNGLCREATESAMPLERSPROC _ptrc_glCreateSamplers = NULL;
PFNGLCREATESHADERPROC _ptrc_glCreateShader = NULL;
PFNGLCREATESHADERPROGRAMVPROC _ptrc_glCreateShaderProgramv = NULL;
PFNGLCREATETEXTURESPROC _ptrc_glCreateTextures = NULL;
PFNGLCREATETRANSFORMFEEDBACKSPROC _ptrc_glCreateTransformFeedbacks = NULL;
PFNGLCREATEVERTEXARRAYSPROC _ptrc_glCreateVertexArrays = NULL;
PFNGLCULLFACEPROC _ptrc_glCullFace = NULL;
PFNGLDEBUGMESSAGECALLBACKPROC _ptrc_glDebugMessageCallback = NULL;
PFNGLDEBUGMESSAGECONTROLPROC _ptrc_glDebugMessageControl = NULL;
PFNGLDEBUGMESSAGEINSERTPROC _ptrc_glDebugMessageInsert = NULL;
PFNGLDELETEBUFFERSPROC _ptrc_glDeleteBuffers = NULL;
PFNGLDELETEFRAMEBUFFERSPROC _ptrc_glDeleteFramebuffers = NULL;
PFNGLDELETEPROGRAMPROC _ptrc_glDeleteProgram = NULL;
PFNGLDELETEPROGRAMPIPELINESPROC _ptrc_glDeleteProgramPipelines = NULL;
PFNGLDELETEQUERIESPROC _ptrc_glDeleteQueries = NULL;
PFNGLDELETERENDERBUFFERSPROC _ptrc_glDeleteRenderbuffers = NULL;
PFNGLDELETESAMPLERSPROC _ptrc_glDeleteSamplers = NULL;
PFNGLDELETESHADERPROC _ptrc_glDeleteShader = NULL;
PFNGLDELETESYNCPROC _ptrc_glDeleteSync = NULL;
PFNGLDELETETEXTURESPROC _ptrc_glDeleteTextures = NULL;
PFNGLDELETETRANSFORMFEEDBACKSPROC _ptrc_glDeleteTransformFeedbacks = NULL;
PFNGLDELETEVERTEXARRAYSPROC _ptrc_glDeleteVertexArrays = NULL;
PFNGLDEPTHFUNCPROC _ptrc_glDepthFunc = NULL;
PFNGLDEPTHMASKPROC _ptrc_glDepthMask = NULL;
PFNGLDEPTHRANGEPROC _ptrc_glDepthRange = NULL;
PFNGLDEPTHRANGEARRAYVPROC _ptrc_glDepthRangeArrayv = NULL;
PFNGLDEPTHRANGEINDEXEDPROC _ptrc_glDepthRangeIndexed = NULL;
PFNGLDEPTHRANGEFPROC _ptrc_glDepthRangef = NULL;
PFNGLDETACHSHADERPROC _ptrc_glDetachShader = NULL;
PFNGLDISABLEPROC _ptrc_glDisable = NULL;
PFNGLDISABLEVERTEXARRAYATTRIBPROC _ptrc_glDisableVertexArrayAttrib = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC _ptrc_glDisableVertexAttribArray = NULL;
PFNGLDISABLEIPROC _ptrc_glDisablei = NULL;
PFNGLDISPATCHCOMPUTEPROC _ptrc_glDispatchCompute = NULL;
PFNGLDISPATCHCOMPUTEINDIRECTPROC _ptrc_glDispatchComputeIndirect = NULL;
PFNGLDRAWARRAYSPROC _ptrc_glDrawArrays = NULL;
PFNGLDRAWARRAYSINDIRECTPROC _ptrc_glDrawArraysIndirect = NULL;
PFNGLDRAWARRAYSINSTANCEDPROC _ptrc_glDrawArraysInstanced = NULL;
PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC _ptrc_glDrawArraysInstancedBaseInstance = NULL;
PFNGLDRAWBUFFERPROC _ptrc_glDrawBuffer = NULL;
PFNGLDRAWBUFFERSPROC _ptrc_glDrawBuffers = NULL;
PFNGLDRAWELEMENTSPROC _ptrc_glDrawElements = NULL;
PFNGLDRAWELEMENTSBASEVERTEXPROC _ptrc_glDrawElementsBaseVertex = NULL;
PFNGLDRAWELEMENTSINDIRECTPROC _ptrc_glDrawElementsIndirect = NULL;
PFNGLDRAWELEMENTSINSTANCEDPROC _ptrc_glDrawElementsInstanced = NULL;
PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC _ptrc_glDrawElementsInstancedBaseInstance = NULL;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC _ptrc_glDrawElementsInstancedBaseVertex = NULL;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC _ptrc_glDrawElementsInstancedBaseVertexBaseInstance = NULL;
PFNGLDRAWRANGEELEMENTSPROC _ptrc_glDrawRangeElements = NULL;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC _ptrc_glDrawRangeElementsBaseVertex = NULL;
PFNGLDRAWTRANSFORMFEEDBACKPROC _ptrc_glDrawTransformFeedback = NULL;
PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC _ptrc_glDrawTransformFeedbackInstanced = NULL;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC _ptrc_glDrawTransformFeedbackStream = NULL;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC _ptrc_glDrawTransformFeedbackStreamInstanced = NULL;
PFNGLENABLEPROC _ptrc_glEnable = NULL;
PFNGLENABLEVERTEXARRAYATTRIBPROC _ptrc_glEnableVertexArrayAttrib = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC _ptrc_glEnableVertexAttribArray = NULL;
PFNGLENABLEIPROC _ptrc_glEnablei = NULL;
PFNGLENDCONDITIONALRENDERPROC _ptrc_glEndConditionalRender = NULL;
PFNGLENDQUERYPROC _ptrc_glEndQuery = NULL;
PFNGLENDQUERYINDEXEDPROC _ptrc_glEndQueryIndexed = NULL;
PFNGLENDTRANSFORMFEEDBACKPROC _ptrc_glEndTransformFeedback = NULL;
PFNGLFENCESYNCPROC _ptrc_glFenceSync = NULL;
PFNGLFINISHPROC _ptrc_glFinish = NULL;
PFNGLFLUSHPROC _ptrc_glFlush = NULL;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC _ptrc_glFlushMappedBufferRange = NULL;
PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC _ptrc_glFlushMappedNamedBufferRange = NULL;
PFNGLFRAMEBUFFERPARAMETERIPROC _ptrc_glFramebufferParameteri = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC _ptrc_glFramebufferRenderbuffer = NULL;
PFNGLFRAMEBUFFERTEXTUREPROC _ptrc_glFramebufferTexture = NULL;
PFNGLFRAMEBUFFERTEXTURE1DPROC _ptrc_glFramebufferTexture1D = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC _ptrc_glFramebufferTexture2D = NULL;
PFNGLFRAMEBUFFERTEXTURE3DPROC _ptrc_glFramebufferTexture3D = NULL;
PFNGLFRAMEBUFFERTEXTURELAYERPROC _ptrc_glFramebufferTextureLayer = NULL;
PFNGLFRONTFACEPROC _ptrc_glFrontFace = NULL;
PFNGLGENBUFFERSPROC _ptrc_glGenBuffers = NULL;
PFNGLGENFRAMEBUFFERSPROC _ptrc_glGenFramebuffers = NULL;
PFNGLGENPROGRAMPIPELINESPROC _ptrc_glGenProgramPipelines = NULL;
PFNGLGENQUERIESPROC _ptrc_glGenQueries = NULL;
PFNGLGENRENDERBUFFERSPROC _ptrc_glGenRenderbuffers = NULL;
PFNGLGENSAMPLERSPROC _ptrc_glGenSamplers = NULL;
PFNGLGENTEXTURESPROC _ptrc_glGenTextures = NULL;
PFNGLGENTRANSFORMFEEDBACKSPROC _ptrc_glGenTransformFeedbacks = NULL;
PFNGLGENVERTEXARRAYSPROC _ptrc_glGenVertexArrays = NULL;
PFNGLGENERATEMIPMAPPROC _ptrc_glGenerateMipmap = NULL;
PFNGLGENERATETEXTUREMIPMAPPROC _ptrc_glGenerateTextureMipmap = NULL;
PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC _ptrc_glGetActiveAtomicCounterBufferiv = NULL;
PFNGLGETACTIVEATTRIBPROC _ptrc_glGetActiveAttrib = NULL;
PFNGLGETACTIVESUBROUTINENAMEPROC _ptrc_glGetActiveSubroutineName = NULL;
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC _ptrc_glGetActiveSubroutineUniformName = NULL;
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC _ptrc_glGetActiveSubroutineUniformiv = NULL;
PFNGLGETACTIVEUNIFORMPROC _ptrc_glGetActiveUniform = NULL;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC _ptrc_glGetActiveUniformBlockName = NULL;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC _ptrc_glGetActiveUniformBlockiv = NULL;
PFNGLGETACTIVEUNIFORMNAMEPROC _ptrc_glGetActiveUniformName = NULL;
PFNGLGETACTIVEUNIFORMSIVPROC _ptrc_glGetActiveUniformsiv = NULL;
PFNGLGETATTACHEDSHADERSPROC _ptrc_glGetAttachedShaders = NULL;
PFNGLGETATTRIBLOCATIONPROC _ptrc_glGetAttribLocation = NULL;
PFNGLGETBOOLEANI_VPROC _ptrc_glGetBooleani_v = NULL;
PFNGLGETBOOLEANVPROC _ptrc_glGetBooleanv = NULL;
PFNGLGETBUFFERPARAMETERI64VPROC _ptrc_glGetBufferParameteri64v = NULL;
PFNGLGETBUFFERPARAMETERIVPROC _ptrc_glGetBufferParameteriv = NULL;
PFNGLGETBUFFERPOINTERVPROC _ptrc_glGetBufferPointerv = NULL;
PFNGLGETBUFFERSUBDATAPROC _ptrc_glGetBufferSubData = NULL;
PFNGLGETCOMPRESSEDTEXIMAGEPROC _ptrc_glGetCompressedTexImage = NULL;
PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC _ptrc_glGetCompressedTextureImage = NULL;
PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC _ptrc_glGetCompressedTextureSubImage = NULL;
PFNGLGETDEBUGMESSAGELOGPROC _ptrc_glGetDebugMessageLog = NULL;
PFNGLGETDOUBLEI_VPROC _ptrc_glGetDoublei_v = NULL;
PFNGLGETDOUBLEVPROC _ptrc_glGetDoublev = NULL;
PFNGLGETERRORPROC _ptrc_glGetError = NULL;
PFNGLGETFLOATI_VPROC _ptrc_glGetFloati_v = NULL;
PFNGLGETFLOATVPROC _ptrc_glGetFloatv = NULL;
PFNGLGETFRAGDATAINDEXPROC _ptrc_glGetFragDataIndex = NULL;
PFNGLGETFRAGDATALOCATIONPROC _ptrc_glGetFragDataLocation = NULL;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC _ptrc_glGetFramebufferAttachmentParameteriv = NULL;
PFNGLGETFRAMEBUFFERPARAMETERIVPROC _ptrc_glGetFramebufferParameteriv = NULL;
PFNGLGETGRAPHICSRESETSTATUSPROC _ptrc_glGetGraphicsResetStatus = NULL;
PFNGLGETINTEGER64I_VPROC _ptrc_glGetInteger64i_v = NULL;
PFNGLGETINTEGER64VPROC _ptrc_glGetInteger64v = NULL;
PFNGLGETINTEGERI_VPROC _ptrc_glGetIntegeri_v = NULL;
PFNGLGETINTEGERVPROC _ptrc_glGetIntegerv = NULL;
PFNGLGETINTERNALFORMATI64VPROC _ptrc_glGetInternalformati64v = NULL;
PFNGLGETINTERNALFORMATIVPROC _ptrc_glGetInternalformativ = NULL;
PFNGLGETMULTISAMPLEFVPROC _ptrc_glGetMultisamplefv = NULL;
PFNGLGETNAMEDBUFFERPARAMETERI64VPROC _ptrc_glGetNamedBufferParameteri64v = NULL;
PFNGLGETNAMEDBUFFERPARAMETERIVPROC _ptrc_glGetNamedBufferParameteriv = NULL;
PFNGLGETNAMEDBUFFERPOINTERVPROC _ptrc_glGetNamedBufferPointerv = NULL;
PFNGLGETNAMEDBUFFERSUBDATAPROC _ptrc_glGetNamedBufferSubData = NULL;
PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC _ptrc_glGetNamedFramebufferAttachmentParameteriv = NULL;
PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC _ptrc_glGetNamedFramebufferParameteriv = NULL;
PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC _ptrc_glGetNamedRenderbufferParameteriv = NULL;
PFNGLGETOBJECTLABELPROC _ptrc_glGetObjectLabel = NULL;
PFNGLGETOBJECTPTRLABELPROC _ptrc_glGetObjectPtrLabel = NULL;
PFNGLGETPOINTERVPROC _ptrc_glGetPointerv = NULL;
PFNGLGETPROGRAMBINARYPROC _ptrc_glGetProgramBinary = NULL;
PFNGLGETPROGRAMINFOLOGPROC _ptrc_glGetProgramInfoLog = NULL;
PFNGLGETPROGRAMINTERFACEIVPROC _ptrc_glGetProgramInterfaceiv = NULL;
PFNGLGETPROGRAMPIPELINEINFOLOGPROC _ptrc_glGetProgramPipelineInfoLog = NULL;
PFNGLGETPROGRAMPIPELINEIVPROC _ptrc_glGetProgramPipelineiv = NULL;
PFNGLGETPROGRAMRESOURCEINDEXPROC _ptrc_glGetProgramResourceIndex = NULL;
PFNGLGETPROGRAMRESOURCELOCATIONPROC _ptrc_glGetProgramResourceLocation = NULL;
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC _ptrc_glGetProgramResourceLocationIndex = NULL;
PFNGLGETPROGRAMRESOURCENAMEPROC _ptrc_glGetProgramResourceName = NULL;
PFNGLGETPROGRAMRESOURCEIVPROC _ptrc_glGetProgramResourceiv = NULL;
PFNGLGETPROGRAMSTAGEIVPROC _ptrc_glGetProgramStageiv = NULL;
PFNGLGETPROGRAMIVPROC _ptrc_glGetProgramiv = NULL;
PFNGLGETQUERYBUFFEROBJECTI64VPROC _ptrc_glGetQueryBufferObjecti64v = NULL;
PFNGLGETQUERYBUFFEROBJECTIVPROC _ptrc_glGetQueryBufferObjectiv = NULL;
PFNGLGETQUERYBUFFEROBJECTUI64VPROC _ptrc_glGetQueryBufferObjectui64v = NULL;
PFNGLGETQUERYBUFFEROBJECTUIVPROC _ptrc_glGetQueryBufferObjectuiv = NULL;
PFNGLGETQUERYINDEXEDIVPROC _ptrc_glGetQueryIndexediv = NULL;
PFNGLGETQUERYOBJECTI64VPROC _ptrc_glGetQueryObjecti64v = NULL;
PFNGLGETQUERYOBJECTIVPROC _ptrc_glGetQueryObjectiv = NULL;
PFNGLGETQUERYOBJECTUI64VPROC _ptrc_glGetQueryObjectui64v = NULL;
PFNGLGETQUERYOBJECTUIVPROC _ptrc_glGetQueryObjectuiv = NULL;
PFNGLGETQUERYIVPROC _ptrc_glGetQueryiv = NULL;
PFNGLGETRENDERBUFFERPARAMETERIVPROC _ptrc_glGetRenderbufferParameteriv = NULL;
PFNGLGETSAMPLERPARAMETERIIVPROC _ptrc_glGetSamplerParameterIiv = NULL;
PFNGLGETSAMPLERPARAMETERIUIVPROC _ptrc_glGetSamplerParameterIuiv = NULL;
PFNGLGETSAMPLERPARAMETERFVPROC _ptrc_glGetSamplerParameterfv = NULL;
PFNGLGETSAMPLERPARAMETERIVPROC _ptrc_glGetSamplerParameteriv = NULL;
PFNGLGETSHADERINFOLOGPROC _ptrc_glGetShaderInfoLog = NULL;
PFNGLGETSHADERPRECISIONFORMATPROC _ptrc_glGetShaderPrecisionFormat = NULL;
PFNGLGETSHADERSOURCEPROC _ptrc_glGetShaderSource = NULL;
PFNGLGETSHADERIVPROC _ptrc_glGetShaderiv = NULL;
PFNGLGETSTRINGPROC _ptrc_glGetString = NULL;
PFNGLGETSTRINGIPROC _ptrc_glGetStringi = NULL;
PFNGLGETSUBROUTINEINDEXPROC _ptrc_glGetSubroutineIndex = NULL;
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC _ptrc_glGetSubroutineUniformLocation = NULL;
PFNGLGETSYNCIVPROC _ptrc_glGetSynciv = NULL;
PFNGLGETTEXIMAGEPROC _ptrc_glGetTexImage = NULL;
PFNGLGETTEXLEVELPARAMETERFVPROC _ptrc_glGetTexLevelParameterfv = NULL;
PFNGLGETTEXLEVELPARAMETERIVPROC _ptrc_glGetTexLevelParameteriv = NULL;
PFNGLGETTEXPARAMETERIIVPROC _ptrc_glGetTexParameterIiv = NULL;
PFNGLGETTEXPARAMETERIUIVPROC _ptrc_glGetTexParameterIuiv = NULL;
PFNGLGETTEXPARAMETERFVPROC _ptrc_glGetTexParameterfv = NULL;
PFNGLGETTEXPARAMETERIVPROC _ptrc_glGetTexParameteriv = NULL;
PFNGLGETTEXTUREIMAGEPROC _ptrc_glGetTextureImage = NULL;
PFNGLGETTEXTURELEVELPARAMETERFVPROC _ptrc_glGetTextureLevelParameterfv = NULL;
PFNGLGETTEXTURELEVELPARAMETERIVPROC _ptrc_glGetTextureLevelParameteriv = NULL;
PFNGLGETTEXTUREPARAMETERIIVPROC _ptrc_glGetTextureParameterIiv = NULL;
PFNGLGETTEXTUREPARAMETERIUIVPROC _ptrc_glGetTextureParameterIuiv = NULL;
PFNGLGETTEXTUREPARAMETERFVPROC _ptrc_glGetTextureParameterfv = NULL;
PFNGLGETTEXTUREPARAMETERIVPROC _ptrc_glGetTextureParameteriv = NULL;
PFNGLGETTEXTURESUBIMAGEPROC _ptrc_glGetTextureSubImage = NULL;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC _ptrc_glGetTransformFeedbackVarying = NULL;
PFNGLGETTRANSFORMFEEDBACKI64_VPROC _ptrc_glGetTransformFeedbacki64_v = NULL;
PFNGLGETTRANSFORMFEEDBACKI_VPROC _ptrc_glGetTransformFeedbacki_v = NULL;
PFNGLGETTRANSFORMFEEDBACKIVPROC _ptrc_glGetTransformFeedbackiv = NULL;
PFNGLGETUNIFORMBLOCKINDEXPROC _ptrc_glGetUniformBlockIndex = NULL;
PFNGLGETUNIFORMINDICESPROC _ptrc_glGetUniformIndices = NULL;
PFNGLGETUNIFORMLOCATIONPROC _ptrc_glGetUniformLocation = NULL;
PFNGLGETUNIFORMSUBROUTINEUIVPROC _ptrc_glGetUniformSubroutineuiv = NULL;
PFNGLGETUNIFORMDVPROC _ptrc_glGetUniformdv = NULL;
PFNGLGETUNIFORMFVPROC _ptrc_glGetUniformfv = NULL;
PFNGLGETUNIFORMIVPROC _ptrc_glGetUniformiv = NULL;
PFNGLGETUNIFORMUIVPROC _ptrc_glGetUniformuiv = NULL;
PFNGLGETVERTEXARRAYINDEXED64IVPROC _ptrc_glGetVertexArrayIndexed64iv = NULL;
PFNGLGETVERTEXARRAYINDEXEDIVPROC _ptrc_glGetVertexArrayIndexediv = NULL;
PFNGLGETVERTEXARRAYIVPROC _ptrc_glGetVertexArrayiv = NULL;
PFNGLGETVERTEXATTRIBIIVPROC _ptrc_glGetVertexAttribIiv = NULL;
PFNGLGETVERTEXATTRIBIUIVPROC _ptrc_glGetVertexAttribIuiv = NULL;
PFNGLGETVERTEXATTRIBLDVPROC _ptrc_glGetVertexAttribLdv = NULL;
PFNGLGETVERTEXATTRIBPOINTERVPROC _ptrc_glGetVertexAttribPointerv = NULL;
PFNGLGETVERTEXATTRIBDVPROC _ptrc_glGetVertexAttribdv = NULL;
PFNGLGETVERTEXATTRIBFVPROC _ptrc_glGetVertexAttribfv = NULL;
PFNGLGETVERTEXATTRIBIVPROC _ptrc_glGetVertexAttribiv = NULL;
PFNGLGETNCOLORTABLEPROC _ptrc_glGetnColorTable = NULL;
PFNGLGETNCOMPRESSEDTEXIMAGEPROC _ptrc_glGetnCompressedTexImage = NULL;
PFNGLGETNCONVOLUTIONFILTERPROC _ptrc_glGetnConvolutionFilter = NULL;
PFNGLGETNHISTOGRAMPROC _ptrc_glGetnHistogram = NULL;
PFNGLGETNMAPDVPROC _ptrc_glGetnMapdv = NULL;
PFNGLGETNMAPFVPROC _ptrc_glGetnMapfv = NULL;
PFNGLGETNMAPIVPROC _ptrc_glGetnMapiv = NULL;
PFNGLGETNMINMAXPROC _ptrc_glGetnMinmax = NULL;
PFNGLGETNPIXELMAPFVPROC _ptrc_glGetnPixelMapfv = NULL;
PFNGLGETNPIXELMAPUIVPROC _ptrc_glGetnPixelMapuiv = NULL;
PFNGLGETNPIXELMAPUSVPROC _ptrc_glGetnPixelMapusv = NULL;
PFNGLGETNPOLYGONSTIPPLEPROC _ptrc_glGetnPolygonStipple = NULL;
PFNGLGETNSEPARABLEFILTERPROC _ptrc_glGetnSeparableFilter = NULL;
PFNGLGETNTEXIMAGEPROC _ptrc_glGetnTexImage = NULL;
PFNGLGETNUNIFORMDVPROC _ptrc_glGetnUniformdv = NULL;
PFNGLGETNUNIFORMFVPROC _ptrc_glGetnUniformfv = NULL;
PFNGLGETNUNIFORMIVPROC _ptrc_glGetnUniformiv = NULL;
PFNGLGETNUNIFORMUIVPROC _ptrc_glGetnUniformuiv = NULL;
PFNGLHINTPROC _ptrc_glHint = NULL;
PFNGLINVALIDATEBUFFERDATAPROC _ptrc_glInvalidateBufferData = NULL;
PFNGLINVALIDATEBUFFERSUBDATAPROC _ptrc_glInvalidateBufferSubData = NULL;
PFNGLINVALIDATEFRAMEBUFFERPROC _ptrc_glInvalidateFramebuffer = NULL;
PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC _ptrc_glInvalidateNamedFramebufferData = NULL;
PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC _ptrc_glInvalidateNamedFramebufferSubData = NULL;
PFNGLINVALIDATESUBFRAMEBUFFERPROC _ptrc_glInvalidateSubFramebuffer = NULL;
PFNGLINVALIDATETEXIMAGEPROC _ptrc_glInvalidateTexImage = NULL;
PFNGLINVALIDATETEXSUBIMAGEPROC _ptrc_glInvalidateTexSubImage = NULL;
PFNGLISBUFFERPROC _ptrc_glIsBuffer = NULL;
PFNGLISENABLEDPROC _ptrc_glIsEnabled = NULL;
PFNGLISENABLEDIPROC _ptrc_glIsEnabledi = NULL;
PFNGLISFRAMEBUFFERPROC _ptrc_glIsFramebuffer = NULL;
PFNGLISPROGRAMPROC _ptrc_glIsProgram = NULL;
PFNGLISPROGRAMPIPELINEPROC _ptrc_glIsProgramPipeline = NULL;
PFNGLISQUERYPROC _ptrc_glIsQuery = NULL;
PFNGLISRENDERBUFFERPROC _ptrc_glIsRenderbuffer = NULL;
PFNGLISSAMPLERPROC _ptrc_glIsSampler = NULL;
PFNGLISSHADERPROC _ptrc_glIsShader = NULL;
PFNGLISSYNCPROC _ptrc_glIsSync = NULL;
PFNGLISTEXTUREPROC _ptrc_glIsTexture = NULL;
PFNGLISTRANSFORMFEEDBACKPROC _ptrc_glIsTransformFeedback = NULL;
PFNGLISVERTEXARRAYPROC _ptrc_glIsVertexArray = NULL;
PFNGLLINEWIDTHPROC _ptrc_glLineWidth = NULL;
PFNGLLINKPROGRAMPROC _ptrc_glLinkProgram = NULL;
PFNGLLOGICOPPROC _ptrc_glLogicOp = NULL;
PFNGLMAPBUFFERPROC _ptrc_glMapBuffer = NULL;
PFNGLMAPBUFFERRANGEPROC _ptrc_glMapBufferRange = NULL;
PFNGLMAPNAMEDBUFFERPROC _ptrc_glMapNamedBuffer = NULL;
PFNGLMAPNAMEDBUFFERRANGEPROC _ptrc_glMapNamedBufferRange = NULL;
PFNGLMEMORYBARRIERPROC _ptrc_glMemoryBarrier = NULL;
PFNGLMEMORYBARRIERBYREGIONPROC _ptrc_glMemoryBarrierByRegion = NULL;
PFNGLMINSAMPLESHADINGPROC _ptrc_glMinSampleShading = NULL;
PFNGLMULTIDRAWARRAYSPROC _ptrc_glMultiDrawArrays = NULL;
PFNGLMULTIDRAWARRAYSINDIRECTPROC _ptrc_glMultiDrawArraysIndirect = NULL;
PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC _ptrc_glMultiDrawArraysIndirectCount = NULL;
PFNGLMULTIDRAWELEMENTSPROC _ptrc_glMultiDrawElements = NULL;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC _ptrc_glMultiDrawElementsBaseVertex = NULL;
PFNGLMULTIDRAWELEMENTSINDIRECTPROC _ptrc_glMultiDrawElementsIndirect = NULL;
PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC _ptrc_glMultiDrawElementsIndirectCount = NULL;
PFNGLMULTITEXCOORDP1UIPROC _ptrc_glMultiTexCoordP1ui = NULL;
PFNGLMULTITEXCOORDP1UIVPROC _ptrc_glMultiTexCoordP1uiv = NULL;
PFNGLMULTITEXCOORDP2UIPROC _ptrc_glMultiTexCoordP2ui = NULL;
PFNGLMULTITEXCOORDP2UIVPROC _ptrc_glMultiTexCoordP2uiv = NULL;
PFNGLMULTITEXCOORDP3UIPROC _ptrc_glMultiTexCoordP3ui = NULL;
PFNGLMULTITEXCOORDP3UIVPROC _ptrc_glMultiTexCoordP3uiv = NULL;
PFNGLMULTITEXCOORDP4UIPROC _ptrc_glMultiTexCoordP4ui = NULL;
PFNGLMULTITEXCOORDP4UIVPROC _ptrc_glMultiTexCoordP4uiv = NULL;
PFNGLNAMEDBUFFERDATAPROC _ptrc_glNamedBufferData = NULL;
PFNGLNAMEDBUFFERSTORAGEPROC _ptrc_glNamedBufferStorage = NULL;
PFNGLNAMEDBUFFERSUBDATAPROC _ptrc_glNamedBufferSubData = NULL;
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC _ptrc_glNamedFramebufferDrawBuffer = NULL;
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC _ptrc_glNamedFramebufferDrawBuffers = NULL;
PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC _ptrc_glNamedFramebufferParameteri = NULL;
PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC _ptrc_glNamedFramebufferReadBuffer = NULL;
PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC _ptrc_glNamedFramebufferRenderbuffer = NULL;
PFNGLNAMEDFRAMEBUFFERTEXTUREPROC _ptrc_glNamedFramebufferTexture = NULL;
PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC _ptrc_glNamedFramebufferTextureLayer = NULL;
PFNGLNAMEDRENDERBUFFERSTORAGEPROC _ptrc_glNamedRenderbufferStorage = NULL;
PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC _ptrc_glNamedRenderbufferStorageMultisample = NULL;
PFNGLNORMALP3UIPROC _ptrc_glNormalP3ui = NULL;
PFNGLNORMALP3UIVPROC _ptrc_glNormalP3uiv = NULL;
PFNGLOBJECTLABELPROC _ptrc_glObjectLabel = NULL;
PFNGLOBJECTPTRLABELPROC _ptrc_glObjectPtrLabel = NULL;
PFNGLPATCHPARAMETERFVPROC _ptrc_glPatchParameterfv = NULL;
PFNGLPATCHPARAMETERIPROC _ptrc_glPatchParameteri = NULL;
PFNGLPAUSETRANSFORMFEEDBACKPROC _ptrc_glPauseTransformFeedback = NULL;
PFNGLPIXELSTOREFPROC _ptrc_glPixelStoref = NULL;
PFNGLPIXELSTOREIPROC _ptrc_glPixelStorei = NULL;
PFNGLPOINTPARAMETERFPROC _ptrc_glPointParameterf = NULL;
PFNGLPOINTPARAMETERFVPROC _ptrc_glPointParameterfv = NULL;
PFNGLPOINTPARAMETERIPROC _ptrc_glPointParameteri = NULL;
PFNGLPOINTPARAMETERIVPROC _ptrc_glPointParameteriv = NULL;
PFNGLPOINTSIZEPROC _ptrc_glPointSize = NULL;
PFNGLPOLYGONMODEPROC _ptrc_glPolygonMode = NULL;
PFNGLPOLYGONOFFSETPROC _ptrc_glPolygonOffset = NULL;
PFNGLPOLYGONOFFSETCLAMPPROC _ptrc_glPolygonOffsetClamp = NULL;
PFNGLPOPDEBUGGROUPPROC _ptrc_glPopDebugGroup = NULL;
PFNGLPRIMITIVERESTARTINDEXPROC _ptrc_glPrimitiveRestartIndex = NULL;
PFNGLPROGRAMBINARYPROC _ptrc_glProgramBinary = NULL;
PFNGLPROGRAMPARAMETERIPROC _ptrc_glProgramParameteri = NULL;
PFNGLPROGRAMUNIFORM1DPROC _ptrc_glProgramUniform1d = NULL;
PFNGLPROGRAMUNIFORM1DVPROC _ptrc_glProgramUniform1dv = NULL;
PFNGLPROGRAMUNIFORM1FPROC _ptrc_glProgramUniform1f = NULL;
PFNGLPROGRAMUNIFORM1FVPROC _ptrc_glProgramUniform1fv = NULL;
PFNGLPROGRAMUNIFORM1IPROC _ptrc_glProgramUniform1i = NULL;
PFNGLPROGRAMUNIFORM1IVPROC _ptrc_glProgramUniform1iv = NULL;
PFNGLPROGRAMUNIFORM1UIPROC _ptrc_glProgramUniform1ui = NULL;
PFNGLPROGRAMUNIFORM1UIVPROC _ptrc_glProgramUniform1uiv = NULL;
PFNGLPROGRAMUNIFORM2DPROC _ptrc_glProgramUniform2d = NULL;
PFNGLPROGRAMUNIFORM2DVPROC _ptrc_glProgramUniform2dv = NULL;
PFNGLPROGRAMUNIFORM2FPROC _ptrc_glProgramUniform2f = NULL;
PFNGLPROGRAMUNIFORM2FVPROC _ptrc_glProgramUniform2fv = NULL;
PFNGLPROGRAMUNIFORM2IPROC _ptrc_glProgramUniform2i = NULL;
PFNGLPROGRAMUNIFORM2IVPROC _ptrc_glProgramUniform2iv = NULL;
PFNGLPROGRAMUNIFORM2UIPROC _ptrc_glProgramUniform2ui = NULL;
PFNGLPROGRAMUNIFORM2UIVPROC _ptrc_glProgramUniform2uiv = NULL;
PFNGLPROGRAMUNIFORM3DPROC _ptrc_glProgramUniform3d = NULL;
PFNGLPROGRAMUNIFORM3DVPROC _ptrc_glProgramUniform3dv = NULL;
PFNGLPROGRAMUNIFORM3FPROC _ptrc_glProgramUniform3f = NULL;
PFNGLPROGRAMUNIFORM3FVPROC _ptrc_glProgramUniform3fv = NULL;
PFNGLPROGRAMUNIFORM3IPROC _ptrc_glProgramUniform3i = NULL;
PFNGLPROGRAMUNIFORM3IVPROC _ptrc_glProgramUniform3iv = NULL;
PFNGLPROGRAMUNIFORM3UIPROC _ptrc_glProgramUniform3ui = NULL;
PFNGLPROGRAMUNIFORM3UIVPROC _ptrc_glProgramUniform3uiv = NULL;
PFNGLPROGRAMUNIFORM4DPROC _ptrc_glProgramUniform4d = NULL;
PFNGLPROGRAMUNIFORM4DVPROC _ptrc_glProgramUniform4dv = NULL;
PFNGLPROGRAMUNIFORM4FPROC _ptrc_glProgramUniform4f = NULL;
PFNGLPROGRAMUNIFORM4FVPROC _ptrc_glProgramUniform4fv = NULL;
PFNGLPROGRAMUNIFORM4IPROC _ptrc_glProgramUniform4i = NULL;
PFNGLPROGRAMUNIFORM4IVPROC _ptrc_glProgramUniform4iv = NULL;
PFNGLPROGRAMUNIFORM4UIPROC _ptrc_glProgramUniform4ui = NULL;
PFNGLPROGRAMUNIFORM4UIVPROC _ptrc_glProgramUniform4uiv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2DVPROC _ptrc_glProgramUniformMatrix2dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2FVPROC _ptrc_glProgramUniformMatrix2fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC _ptrc_glProgramUniformMatrix2x3dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC _ptrc_glProgramUniformMatrix2x3fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC _ptrc_glProgramUniformMatrix2x4dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC _ptrc_glProgramUniformMatrix2x4fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3DVPROC _ptrc_glProgramUniformMatrix3dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC _ptrc_glProgramUniformMatrix3fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC _ptrc_glProgramUniformMatrix3x2dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC _ptrc_glProgramUniformMatrix3x2fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC _ptrc_glProgramUniformMatrix3x4dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC _ptrc_glProgramUniformMatrix3x4fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4DVPROC _ptrc_glProgramUniformMatrix4dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4FVPROC _ptrc_glProgramUniformMatrix4fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC _ptrc_glProgramUniformMatrix4x2dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC _ptrc_glProgramUniformMatrix4x2fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC _ptrc_glProgramUniformMatrix4x3dv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC _ptrc_glProgramUniformMatrix4x3fv = NULL;
PFNGLPROVOKINGVERTEXPROC _ptrc_glProvokingVertex = NULL;
PFNGLPUSHDEBUGGROUPPROC _ptrc_glPushDebugGroup = NULL;
PFNGLQUERYCOUNTERPROC _ptrc_glQueryCounter = NULL;
PFNGLREADBUFFERPROC _ptrc_glReadBuffer = NULL;
PFNGLREADPIXELSPROC _ptrc_glReadPixels = NULL;
PFNGLREADNPIXELSPROC _ptrc_glReadnPixels = NULL;
PFNGLRELEASESHADERCOMPILERPROC _ptrc_glReleaseShaderCompiler = NULL;
PFNGLRENDERBUFFERSTORAGEPROC _ptrc_glRenderbufferStorage = NULL;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC _ptrc_glRenderbufferStorageMultisample = NULL;
PFNGLRESUMETRANSFORMFEEDBACKPROC _ptrc_glResumeTransformFeedback = NULL;
PFNGLSAMPLECOVERAGEPROC _ptrc_glSampleCoverage = NULL;
PFNGLSAMPLEMASKIPROC _ptrc_glSampleMaski = NULL;
PFNGLSAMPLERPARAMETERIIVPROC _ptrc_glSamplerParameterIiv = NULL;
PFNGLSAMPLERPARAMETERIUIVPROC _ptrc_glSamplerParameterIuiv = NULL;
PFNGLSAMPLERPARAMETERFPROC _ptrc_glSamplerParameterf = NULL;
PFNGLSAMPLERPARAMETERFVPROC _ptrc_glSamplerParameterfv = NULL;
PFNGLSAMPLERPARAMETERIPROC _ptrc_glSamplerParameteri = NULL;
PFNGLSAMPLERPARAMETERIVPROC _ptrc_glSamplerParameteriv = NULL;
PFNGLSCISSORPROC _ptrc_glScissor = NULL;
PFNGLSCISSORARRAYVPROC _ptrc_glScissorArrayv = NULL;
PFNGLSCISSORINDEXEDPROC _ptrc_glScissorIndexed = NULL;
PFNGLSCISSORINDEXEDVPROC _ptrc_glScissorIndexedv = NULL;
PFNGLSECONDARYCOLORP3UIPROC _ptrc_glSecondaryColorP3ui = NULL;
PFNGLSECONDARYCOLORP3UIVPROC _ptrc_glSecondaryColorP3uiv = NULL;
PFNGLSHADERBINARYPROC _ptrc_glShaderBinary = NULL;
PFNGLSHADERSOURCEPROC _ptrc_glShaderSource = NULL;
PFNGLSHADERSTORAGEBLOCKBINDINGPROC _ptrc_glShaderStorageBlockBinding = NULL;
PFNGLSPECIALIZESHADERPROC _ptrc_glSpecializeShader = NULL;
PFNGLSTENCILFUNCPROC _ptrc_glStencilFunc = NULL;
PFNGLSTENCILFUNCSEPARATEPROC _ptrc_glStencilFuncSeparate = NULL;
PFNGLSTENCILMASKPROC _ptrc_glStencilMask = NULL;
PFNGLSTENCILMASKSEPARATEPROC _ptrc_glStencilMaskSeparate = NULL;
PFNGLSTENCILOPPROC _ptrc_glStencilOp = NULL;
PFNGLSTENCILOPSEPARATEPROC _ptrc_glStencilOpSeparate = NULL;
PFNGLTEXBUFFERPROC _ptrc_glTexBuffer = NULL;
PFNGLTEXBUFFERRANGEPROC _ptrc_glTexBufferRange = NULL;
PFNGLTEXCOORDP1UIPROC _ptrc_glTexCoordP1ui = NULL;
PFNGLTEXCOORDP1UIVPROC _ptrc_glTexCoordP1uiv = NULL;
PFNGLTEXCOORDP2UIPROC _ptrc_glTexCoordP2ui = NULL;
PFNGLTEXCOORDP2UIVPROC _ptrc_glTexCoordP2uiv = NULL;
PFNGLTEXCOORDP3UIPROC _ptrc_glTexCoordP3ui = NULL;
PFNGLTEXCOORDP3UIVPROC _ptrc_glTexCoordP3uiv = NULL;
PFNGLTEXCOORDP4UIPROC _ptrc_glTexCoordP4ui = NULL;
PFNGLTEXCOORDP4UIVPROC _ptrc_glTexCoordP4uiv = NULL;
PFNGLTEXIMAGE1DPROC _ptrc_glTexImage1D = NULL;
PFNGLTEXIMAGE2DPROC _ptrc_glTexImage2D = NULL;
PFNGLTEXIMAGE2DMULTISAMPLEPROC _ptrc_glTexImage2DMultisample = NULL;
PFNGLTEXIMAGE3DPROC _ptrc_glTexImage3D = NULL;
PFNGLTEXIMAGE3DMULTISAMPLEPROC _ptrc_glTexImage3DMultisample = NULL;
PFNGLTEXPARAMETERIIVPROC _ptrc_glTexParameterIiv = NULL;
PFNGLTEXPARAMETERIUIVPROC _ptrc_glTexParameterIuiv = NULL;
PFNGLTEXPARAMETERFPROC _ptrc_glTexParameterf = NULL;
PFNGLTEXPARAMETERFVPROC _ptrc_glTexParameterfv = NULL;
PFNGLTEXPARAMETERIPROC _ptrc_glTexParameteri = NULL;
PFNGLTEXPARAMETERIVPROC _ptrc_glTexParameteriv = NULL;
PFNGLTEXSTORAGE1DPROC _ptrc_glTexStorage1D = NULL;
PFNGLTEXSTORAGE2DPROC _ptrc_glTexStorage2D = NULL;
PFNGLTEXSTORAGE2DMULTISAMPLEPROC _ptrc_glTexStorage2DMultisample = NULL;
PFNGLTEXSTORAGE3DPROC _ptrc_glTexStorage3D = NULL;
PFNGLTEXSTORAGE3DMULTISAMPLEPROC _ptrc_glTexStorage3DMultisample = NULL;
PFNGLTEXSUBIMAGE1DPROC _ptrc_glTexSubImage1D = NULL;
PFNGLTEXSUBIMAGE2DPROC _ptrc_glTexSubImage2D = NULL;
PFNGLTEXSUBIMAGE3DPROC _ptrc_glTexSubImage3D = NULL;
PFNGLTEXTUREBARRIERPROC _ptrc_glTextureBarrier = NULL;
PFNGLTEXTUREBUFFERPROC _ptrc_glTextureBuffer = NULL;
PFNGLTEXTUREBUFFERRANGEPROC _ptrc_glTextureBufferRange = NULL;
PFNGLTEXTUREPARAMETERIIVPROC _ptrc_glTextureParameterIiv = NULL;
PFNGLTEXTUREPARAMETERIUIVPROC _ptrc_glTextureParameterIuiv = NULL;
PFNGLTEXTUREPARAMETERFPROC _ptrc_glTextureParameterf = NULL;
PFNGLTEXTUREPARAMETERFVPROC _ptrc_glTextureParameterfv = NULL;
PFNGLTEXTUREPARAMETERIPROC _ptrc_glTextureParameteri = NULL;
PFNGLTEXTUREPARAMETERIVPROC _ptrc_glTextureParameteriv = NULL;
PFNGLTEXTURESTORAGE1DPROC _ptrc_glTextureStorage1D = NULL;
PFNGLTEXTURESTORAGE2DPROC _ptrc_glTextureStorage2D = NULL;
PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC _ptrc_glTextureStorage2DMultisample = NULL;
PFNGLTEXTURESTORAGE3DPROC _ptrc_glTextureStorage3D = NULL;
PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC _ptrc_glTextureStorage3DMultisample = NULL;
PFNGLTEXTURESUBIMAGE1DPROC _ptrc_glTextureSubImage1D = NULL;
PFNGLTEXTURESUBIMAGE2DPROC _ptrc_glTextureSubImage2D = NULL;
PFNGLTEXTURESUBIMAGE3DPROC _ptrc_glTextureSubImage3D = NULL;
PFNGLTEXTUREVIEWPROC _ptrc_glTextureView = NULL;
PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC _ptrc_glTransformFeedbackBufferBase = NULL;
PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC _ptrc_glTransformFeedbackBufferRange = NULL;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC _ptrc_glTransformFeedbackVaryings = NULL;
PFNGLUNIFORM1DPROC _ptrc_glUniform1d = NULL;
PFNGLUNIFORM1DVPROC _ptrc_glUniform1dv = NULL;
PFNGLUNIFORM1FPROC _ptrc_glUniform1f = NULL;
PFNGLUNIFORM1FVPROC _ptrc_glUniform1fv = NULL;
PFNGLUNIFORM1IPROC _ptrc_glUniform1i = NULL;
PFNGLUNIFORM1IVPROC _ptrc_glUniform1iv = NULL;
PFNGLUNIFORM1UIPROC _ptrc_glUniform1ui = NULL;
PFNGLUNIFORM1UIVPROC _ptrc_glUniform1uiv = NULL;
PFNGLUNIFORM2DPROC _ptrc_glUniform2d = NULL;
PFNGLUNIFORM2DVPROC _ptrc_glUniform2dv = NULL;
PFNGLUNIFORM2FPROC _ptrc_glUniform2f = NULL;
PFNGLUNIFORM2FVPROC _ptrc_glUniform2fv = NULL;
PFNGLUNIFORM2IPROC _ptrc_glUniform2i = NULL;
PFNGLUNIFORM2IVPROC _ptrc_glUniform2iv = NULL;
PFNGLUNIFORM2UIPROC _ptrc_glUniform2ui = NULL;
PFNGLUNIFORM2UIVPROC _ptrc_glUniform2uiv = NULL;
PFNGLUNIFORM3DPROC _ptrc_glUniform3d = NULL;
PFNGLUNIFORM3DVPROC _ptrc_glUniform3dv = NULL;
PFNGLUNIFORM3FPROC _ptrc_glUniform3f = NULL;
PFNGLUNIFORM3FVPROC _ptrc_glUniform3fv = NULL;
PFNGLUNIFORM3IPROC _ptrc_glUniform3i = NULL;
PFNGLUNIFORM3IVPROC _ptrc_glUniform3iv = NULL;
PFNGLUNIFORM3UIPROC _ptrc_glUniform3ui = NULL;
PFNGLUNIFORM3UIVPROC _ptrc_glUniform3uiv = NULL;
PFNGLUNIFORM4DPROC _ptrc_glUniform4d = NULL;
PFNGLUNIFORM4DVPROC _ptrc_glUniform4dv = NULL;
PFNGLUNIFORM4FPROC _ptrc_glUniform4f = NULL;
PFNGLUNIFORM4FVPROC _ptrc_glUniform4fv = NULL;
PFNGLUNIFORM4IPROC _ptrc_glUniform4i = NULL;
PFNGLUNIFORM4IVPROC _ptrc_glUniform4iv = NULL;
PFNGLUNIFORM4UIPROC _ptrc_glUniform4ui = NULL;
PFNGLUNIFORM4UIVPROC _ptrc_glUniform4uiv = NULL;
PFNGLUNIFORMBLOCKBINDINGPROC _ptrc_glUniformBlockBinding = NULL;
PFNGLUNIFORMMATRIX2DVPROC _ptrc_glUniformMatrix2dv = NULL;
PFNGLUNIFORMMATRIX2FVPROC _ptrc_glUniformMatrix2fv = NULL;
PFNGLUNIFORMMATRIX2X3DVPROC _ptrc_glUniformMatrix2x3dv = NULL;
PFNGLUNIFORMMATRIX2X3FVPROC _ptrc_glUniformMatrix2x3fv = NULL;
PFNGLUNIFORMMATRIX2X4DVPROC _ptrc_glUniformMatrix2x4dv = NULL;
PFNGLUNIFORMMATRIX2X4FVPROC _ptrc_glUniformMatrix2x4fv = NULL;
PFNGLUNIFORMMATRIX3DVPROC _ptrc_glUniformMatrix3dv = NULL;
PFNGLUNIFORMMATRIX3FVPROC _ptrc_glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX3X2DVPROC _ptrc_glUniformMatrix3x2dv = NULL;
PFNGLUNIFORMMATRIX3X2FVPROC _ptrc_glUniformMatrix3x2fv = NULL;
PFNGLUNIFORMMATRIX3X4DVPROC _ptrc_glUniformMatrix3x4dv = NULL;
PFNGLUNIFORMMATRIX3X4FVPROC _ptrc_glUniformMatrix3x4fv = NULL;
PFNGLUNIFORMMATRIX4DVPROC _ptrc_glUniformMatrix4dv = NULL;
PFNGLUNIFORMMATRIX4FVPROC _ptrc_glUniformMatrix4fv = NULL;
PFNGLUNIFORMMATRIX4X2DVPROC _ptrc_glUniformMatrix4x2dv = NULL;
PFNGLUNIFORMMATRIX4X2FVPROC _ptrc_glUniformMatrix4x2fv = NULL;
PFNGLUNIFORMMATRIX4X3DVPROC _ptrc_glUniformMatrix4x3dv = NULL;
PFNGLUNIFORMMATRIX4X3FVPROC _ptrc_glUniformMatrix4x3fv = NULL;
PFNGLUNIFORMSUBROUTINESUIVPROC _ptrc_glUniformSubroutinesuiv = NULL;
PFNGLUNMAPBUFFERPROC _ptrc_glUnmapBuffer = NULL;
PFNGLUNMAPNAMEDBUFFERPROC _ptrc_glUnmapNamedBuffer = NULL;
PFNGLUSEPROGRAMPROC _ptrc_glUseProgram = NULL;
PFNGLUSEPROGRAMSTAGESPROC _ptrc_glUseProgramStages = NULL;
PFNGLVALIDATEPROGRAMPROC _ptrc_glValidateProgram = NULL;
PFNGLVALIDATEPROGRAMPIPELINEPROC _ptrc_glValidateProgramPipeline = NULL;
PFNGLVERTEXARRAYATTRIBBINDINGPROC _ptrc_glVertexArrayAttribBinding = NULL;
PFNGLVERTEXARRAYATTRIBFORMATPROC _ptrc_glVertexArrayAttribFormat = NULL;
PFNGLVERTEXARRAYATTRIBIFORMATPROC _ptrc_glVertexArrayAttribIFormat = NULL;
PFNGLVERTEXARRAYATTRIBLFORMATPROC _ptrc_glVertexArrayAttribLFormat = NULL;
PFNGLVERTEXARRAYBINDINGDIVISORPROC _ptrc_glVertexArrayBindingDivisor = NULL;
PFNGLVERTEXARRAYELEMENTBUFFERPROC _ptrc_glVertexArrayElementBuffer = NULL;
PFNGLVERTEXARRAYVERTEXBUFFERPROC _ptrc_glVertexArrayVertexBuffer = NULL;
PFNGLVERTEXARRAYVERTEXBUFFERSPROC _ptrc_glVertexArrayVertexBuffers = NULL;
PFNGLVERTEXATTRIB1DPROC _ptrc_glVertexAttrib1d = NULL;
PFNGLVERTEXATTRIB1DVPROC _ptrc_glVertexAttrib1dv = NULL;
PFNGLVERTEXATTRIB1FPROC _ptrc_glVertexAttrib1f = NULL;
PFNGLVERTEXATTRIB1FVPROC _ptrc_glVertexAttrib1fv = NULL;
PFNGLVERTEXATTRIB1SPROC _ptrc_glVertexAttrib1s = NULL;
PFNGLVERTEXATTRIB1SVPROC _ptrc_glVertexAttrib1sv = NULL;
PFNGLVERTEXATTRIB2DPROC _ptrc_glVertexAttrib2d = NULL;
PFNGLVERTEXATTRIB2DVPROC _ptrc_glVertexAttrib2dv = NULL;
PFNGLVERTEXATTRIB2FPROC _ptrc_glVertexAttrib2f = NULL;
PFNGLVERTEXATTRIB2FVPROC _ptrc_glVertexAttrib2fv = NULL;
PFNGLVERTEXATTRIB2SPROC _ptrc_glVertexAttrib2s = NULL;
PFNGLVERTEXATTRIB2SVPROC _ptrc_glVertexAttrib2sv = NULL;
PFNGLVERTEXATTRIB3DPROC _ptrc_glVertexAttrib3d = NULL;
PFNGLVERTEXATTRIB3DVPROC _ptrc_glVertexAttrib3dv = NULL;
PFNGLVERTEXATTRIB3FPROC _ptrc_glVertexAttrib3f = NULL;
PFNGLVERTEXATTRIB3FVPROC _ptrc_glVertexAttrib3fv = NULL;
PFNGLVERTEXATTRIB3SPROC _ptrc_glVertexAttrib3s = NULL;
PFNGLVERTEXATTRIB3SVPROC _ptrc_glVertexAttrib3sv = NULL;
PFNGLVERTEXATTRIB4NBVPROC _ptrc_glVertexAttrib4Nbv = NULL;
PFNGLVERTEXATTRIB4NIVPROC _ptrc_glVertexAttrib4Niv = NULL;
PFNGLVERTEXATTRIB4NSVPROC _ptrc_glVertexAttrib4Nsv = NULL;
PFNGLVERTEXATTRIB4NUBPROC _ptrc_glVertexAttrib4Nub = NULL;
PFNGLVERTEXATTRIB4NUBVPROC _ptrc_glVertexAttrib4Nubv = NULL;
PFNGLVERTEXATTRIB4NUIVPROC _ptrc_glVertexAttrib4Nuiv = NULL;
PFNGLVERTEXATTRIB4NUSVPROC _ptrc_glVertexAttrib4Nusv = NULL;
PFNGLVERTEXATTRIB4BVPROC _ptrc_glVertexAttrib4bv = NULL;
PFNGLVERTEXATTRIB4DPROC _ptrc_glVertexAttrib4d = NULL;
PFNGLVERTEXATTRIB4DVPROC _ptrc_glVertexAttrib4dv = NULL;
PFNGLVERTEXATTRIB4FPROC _ptrc_glVertexAttrib4f = NULL;
PFNGLVERTEXATTRIB4FVPROC _ptrc_glVertexAttrib4fv = NULL;
PFNGLVERTEXATTRIB4IVPROC _ptrc_glVertexAttrib4iv = NULL;
PFNGLVERTEXATTRIB4SPROC _ptrc_glVertexAttrib4s = NULL;
PFNGLVERTEXATTRIB4SVPROC _ptrc_glVertexAttrib4sv = NULL;
PFNGLVERTEXATTRIB4UBVPROC _ptrc_glVertexAttrib4ubv = NULL;
PFNGLVERTEXATTRIB4UIVPROC _ptrc_glVertexAttrib4uiv = NULL;
PFNGLVERTEXATTRIB4USVPROC _ptrc_glVertexAttrib4usv = NULL;
PFNGLVERTEXATTRIBBINDINGPROC _ptrc_glVertexAttribBinding = NULL;
PFNGLVERTEXATTRIBDIVISORPROC _ptrc_glVertexAttribDivisor = NULL;
PFNGLVERTEXATTRIBFORMATPROC _ptrc_glVertexAttribFormat = NULL;
PFNGLVERTEXATTRIBI1IPROC _ptrc_glVertexAttribI1i = NULL;
PFNGLVERTEXATTRIBI1IVPROC _ptrc_glVertexAttribI1iv = NULL;
PFNGLVERTEXATTRIBI1UIPROC _ptrc_glVertexAttribI1ui = NULL;
PFNGLVERTEXATTRIBI1UIVPROC _ptrc_glVertexAttribI1uiv = NULL;
PFNGLVERTEXATTRIBI2IPROC _ptrc_glVertexAttribI2i = NULL;
PFNGLVERTEXATTRIBI2IVPROC _ptrc_glVertexAttribI2iv = NULL;
PFNGLVERTEXATTRIBI2UIPROC _ptrc_glVertexAttribI2ui = NULL;
PFNGLVERTEXATTRIBI2UIVPROC _ptrc_glVertexAttribI2uiv = NULL;
PFNGLVERTEXATTRIBI3IPROC _ptrc_glVertexAttribI3i = NULL;
PFNGLVERTEXATTRIBI3IVPROC _ptrc_glVertexAttribI3iv = NULL;
PFNGLVERTEXATTRIBI3UIPROC _ptrc_glVertexAttribI3ui = NULL;
PFNGLVERTEXATTRIBI3UIVPROC _ptrc_glVertexAttribI3uiv = NULL;
PFNGLVERTEXATTRIBI4BVPROC _ptrc_glVertexAttribI4bv = NULL;
PFNGLVERTEXATTRIBI4IPROC _ptrc_glVertexAttribI4i = NULL;
PFNGLVERTEXATTRIBI4IVPROC _ptrc_glVertexAttribI4iv = NULL;
PFNGLVERTEXATTRIBI4SVPROC _ptrc_glVertexAttribI4sv = NULL;
PFNGLVERTEXATTRIBI4UBVPROC _ptrc_glVertexAttribI4ubv = NULL;
PFNGLVERTEXATTRIBI4UIPROC _ptrc_glVertexAttribI4ui = NULL;
PFNGLVERTEXATTRIBI4UIVPROC _ptrc_glVertexAttribI4uiv = NULL;
PFNGLVERTEXATTRIBI4USVPROC _ptrc_glVertexAttribI4usv = NULL;
PFNGLVERTEXATTRIBIFORMATPROC _ptrc_glVertexAttribIFormat = NULL;
PFNGLVERTEXATTRIBIPOINTERPROC _ptrc_glVertexAttribIPointer = NULL;
PFNGLVERTEXATTRIBL1DPROC _ptrc_glVertexAttribL1d = NULL;
PFNGLVERTEXATTRIBL1DVPROC _ptrc_glVertexAttribL1dv = NULL;
PFNGLVERTEXATTRIBL2DPROC _ptrc_glVertexAttribL2d = NULL;
PFNGLVERTEXATTRIBL2DVPROC _ptrc_glVertexAttribL2dv = NULL;
PFNGLVERTEXATTRIBL3DPROC _ptrc_glVertexAttribL3d = NULL;
PFNGLVERTEXATTRIBL3DVPROC _ptrc_glVertexAttribL3dv = NULL;
PFNGLVERTEXATTRIBL4DPROC _ptrc_glVertexAttribL4d = NULL;
PFNGLVERTEXATTRIBL4DVPROC _ptrc_glVertexAttribL4dv = NULL;
PFNGLVERTEXATTRIBLFORMATPROC _ptrc_glVertexAttribLFormat = NULL;
PFNGLVERTEXATTRIBLPOINTERPROC _ptrc_glVertexAttribLPointer = NULL;
PFNGLVERTEXATTRIBP1UIPROC _ptrc_glVertexAttribP1ui = NULL;
PFNGLVERTEXATTRIBP1UIVPROC _ptrc_glVertexAttribP1uiv = NULL;
PFNGLVERTEXATTRIBP2UIPROC _ptrc_glVertexAttribP2ui = NULL;
PFNGLVERTEXATTRIBP2UIVPROC _ptrc_glVertexAttribP2uiv = NULL;
PFNGLVERTEXATTRIBP3UIPROC _ptrc_glVertexAttribP3ui = NULL;
PFNGLVERTEXATTRIBP3UIVPROC _ptrc_glVertexAttribP3uiv = NULL;
PFNGLVERTEXATTRIBP4UIPROC _ptrc_glVertexAttribP4ui = NULL;
PFNGLVERTEXATTRIBP4UIVPROC _ptrc_glVertexAttribP4uiv = NULL;
PFNGLVERTEXATTRIBPOINTERPROC _ptrc_glVertexAttribPointer = NULL;
PFNGLVERTEXBINDINGDIVISORPROC _ptrc_glVertexBindingDivisor = NULL;
PFNGLVERTEXP2UIPROC _ptrc_glVertexP2ui = NULL;
PFNGLVERTEXP2UIVPROC _ptrc_glVertexP2uiv = NULL;
PFNGLVERTEXP3UIPROC _ptrc_glVertexP3ui = NULL;
PFNGLVERTEXP3UIVPROC _ptrc_glVertexP3uiv = NULL;
PFNGLVERTEXP4UIPROC _ptrc_glVertexP4ui = NULL;
PFNGLVERTEXP4UIVPROC _ptrc_glVertexP4uiv = NULL;
PFNGLVIEWPORTPROC _ptrc_glViewport = NULL;
PFNGLVIEWPORTARRAYVPROC _ptrc_glViewportArrayv = NULL;
PFNGLVIEWPORTINDEXEDFPROC _ptrc_glViewportIndexedf = NULL;
PFNGLVIEWPORTINDEXEDFVPROC _ptrc_glViewportIndexedfv = NULL;
PFNGLWAITSYNCPROC _ptrc_glWaitSync = NULL;

int OGL_VERSION_MAJOR = 0;
int OGL_VERSION_MINOR = 0;
int OGL_VERSION_1_0 = 0;
int OGL_VERSION_1_1 = 0;
int OGL_VERSION_1_2 = 0;
int OGL_VERSION_1_3 = 0;
int OGL_VERSION_1_4 = 0;
int OGL_VERSION_1_5 = 0;
int OGL_VERSION_2_0 = 0;
int OGL_VERSION_2_1 = 0;
int OGL_VERSION_3_0 = 0;
int OGL_VERSION_3_1 = 0;
int OGL_VERSION_3_2 = 0;
int OGL_VERSION_3_3 = 0;
int OGL_VERSION_4_0 = 0;
int OGL_VERSION_4_1 = 0;
int OGL_VERSION_4_2 = 0;
int OGL_VERSION_4_3 = 0;
int OGL_VERSION_4_4 = 0;
int OGL_VERSION_4_5 = 0;
int OGL_VERSION_4_6 = 0;

bool OGL_LOADED_CORE = false;

#include <cstring>

static bool load_base() {
  if (OGL_LOADED_CORE) return true;
  // load core functions
  _ptrc_glGetString   = reinterpret_cast<PFNGLGETSTRINGPROC>(::glGetProcAddress("glGetString"));
  // done
  return (OGL_LOADED_CORE = (_ptrc_glGetString != NULL));
}

static bool load_v_1_0() { 
  if(!OGL_VERSION_1_0) return false;
  _ptrc_glCullFace               = (PFNGLCULLFACEPROC)::glGetProcAddress("glCullFace");
  _ptrc_glFrontFace              = (PFNGLFRONTFACEPROC)::glGetProcAddress("glFrontFace");
  _ptrc_glHint                   = (PFNGLHINTPROC)::glGetProcAddress("glHint");
  _ptrc_glLineWidth              = (PFNGLLINEWIDTHPROC)::glGetProcAddress("glLineWidth");
  _ptrc_glPointSize              = (PFNGLPOINTSIZEPROC)::glGetProcAddress("glPointSize");
  _ptrc_glPolygonMode            = (PFNGLPOLYGONMODEPROC)::glGetProcAddress("glPolygonMode");
  _ptrc_glScissor                = (PFNGLSCISSORPROC)::glGetProcAddress("glScissor");
  _ptrc_glTexParameterf          = (PFNGLTEXPARAMETERFPROC)::glGetProcAddress("glTexParameterf");
  _ptrc_glTexParameterfv         = (PFNGLTEXPARAMETERFVPROC)::glGetProcAddress("glTexParameterfv");
  _ptrc_glTexParameteri          = (PFNGLTEXPARAMETERIPROC)::glGetProcAddress("glTexParameteri");
  _ptrc_glTexParameteriv         = (PFNGLTEXPARAMETERIVPROC)::glGetProcAddress("glTexParameteriv");
  _ptrc_glTexImage1D             = (PFNGLTEXIMAGE1DPROC)::glGetProcAddress("glTexImage1D");
  _ptrc_glTexImage2D             = (PFNGLTEXIMAGE2DPROC)::glGetProcAddress("glTexImage2D");
  _ptrc_glDrawBuffer             = (PFNGLDRAWBUFFERPROC)::glGetProcAddress("glDrawBuffer");
  _ptrc_glClear                  = (PFNGLCLEARPROC)::glGetProcAddress("glClear");
  _ptrc_glClearColor             = (PFNGLCLEARCOLORPROC)::glGetProcAddress("glClearColor");
  _ptrc_glClearStencil           = (PFNGLCLEARSTENCILPROC)::glGetProcAddress("glClearStencil");
  _ptrc_glClearDepth             = (PFNGLCLEARDEPTHPROC)::glGetProcAddress("glClearDepth");
  _ptrc_glStencilMask            = (PFNGLSTENCILMASKPROC)::glGetProcAddress("glStencilMask");
  _ptrc_glColorMask              = (PFNGLCOLORMASKPROC)::glGetProcAddress("glColorMask");
  _ptrc_glDepthMask              = (PFNGLDEPTHMASKPROC)::glGetProcAddress("glDepthMask");
  _ptrc_glDisable                = (PFNGLDISABLEPROC)::glGetProcAddress("glDisable");
  _ptrc_glEnable                 = (PFNGLENABLEPROC)::glGetProcAddress("glEnable");
  _ptrc_glFinish                 = (PFNGLFINISHPROC)::glGetProcAddress("glFinish");
  _ptrc_glFlush                  = (PFNGLFLUSHPROC)::glGetProcAddress("glFlush");
  _ptrc_glBlendFunc              = (PFNGLBLENDFUNCPROC)::glGetProcAddress("glBlendFunc");
  _ptrc_glLogicOp                = (PFNGLLOGICOPPROC)::glGetProcAddress("glLogicOp");
  _ptrc_glStencilFunc            = (PFNGLSTENCILFUNCPROC)::glGetProcAddress("glStencilFunc");
  _ptrc_glStencilOp              = (PFNGLSTENCILOPPROC)::glGetProcAddress("glStencilOp");
  _ptrc_glDepthFunc              = (PFNGLDEPTHFUNCPROC)::glGetProcAddress("glDepthFunc");
  _ptrc_glPixelStoref            = (PFNGLPIXELSTOREFPROC)::glGetProcAddress("glPixelStoref");
  _ptrc_glPixelStorei            = (PFNGLPIXELSTOREIPROC)::glGetProcAddress("glPixelStorei");
  _ptrc_glReadBuffer             = (PFNGLREADBUFFERPROC)::glGetProcAddress("glReadBuffer");
  _ptrc_glReadPixels             = (PFNGLREADPIXELSPROC)::glGetProcAddress("glReadPixels");
  _ptrc_glGetBooleanv            = (PFNGLGETBOOLEANVPROC)::glGetProcAddress("glGetBooleanv");
  _ptrc_glGetDoublev             = (PFNGLGETDOUBLEVPROC)::glGetProcAddress("glGetDoublev");
  _ptrc_glGetError               = (PFNGLGETERRORPROC)::glGetProcAddress("glGetError");
  _ptrc_glGetFloatv              = (PFNGLGETFLOATVPROC)::glGetProcAddress("glGetFloatv");
  _ptrc_glGetIntegerv            = (PFNGLGETINTEGERVPROC)::glGetProcAddress("glGetIntegerv");
  _ptrc_glGetString              = (PFNGLGETSTRINGPROC)::glGetProcAddress("glGetString");
  _ptrc_glGetTexImage            = (PFNGLGETTEXIMAGEPROC)::glGetProcAddress("glGetTexImage");
  _ptrc_glGetTexParameterfv      = (PFNGLGETTEXPARAMETERFVPROC)::glGetProcAddress("glGetTexParameterfv");
  _ptrc_glGetTexParameteriv      = (PFNGLGETTEXPARAMETERIVPROC)::glGetProcAddress("glGetTexParameteriv");
  _ptrc_glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC)::glGetProcAddress("glGetTexLevelParameterfv");
  _ptrc_glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC)::glGetProcAddress("glGetTexLevelParameteriv");
  _ptrc_glIsEnabled              = (PFNGLISENABLEDPROC)::glGetProcAddress("glIsEnabled");
  _ptrc_glDepthRange             = (PFNGLDEPTHRANGEPROC)::glGetProcAddress("glDepthRange");
  _ptrc_glViewport               = (PFNGLVIEWPORTPROC)::glGetProcAddress("glViewport");
  return true;
}

static void load_v_1_1() { } 
static void load_v_1_2() { } 
static void load_v_1_3() { } 
static void load_v_1_4() { } 
static void load_v_1_5() { } 
static void load_v_2_0() { } 
static void load_v_2_1() { } 
static void load_v_3_0() { } 
static void load_v_3_1() { } 
static void load_v_3_2() { } 
static void load_v_3_3() { } 
static void load_v_4_0() { } 
static void load_v_4_1() { } 
static void load_v_4_2() { } 
static void load_v_4_3() { } 
static void load_v_4_4() { } 
static void load_v_4_5() { } 
static void load_v_4_6() { }

static void load_exts() { }

bool glVersion(int& major, int& minor) {
  load_base();
  // skip the line
  if (OGL_VERSION_MAJOR && OGL_VERSION_MINOR) {
    major = OGL_VERSION_MAJOR;
    minor = OGL_VERSION_MINOR;
    return true;
  }
  
  const char* version;
  const char* prefixes[] = {"OpenGL ES-CM ", "OpenGL ES-CL ", "OpenGL ES ", NULL};
  version = (const char*) ::glGetString(GL_VERSION);
  if (!version) return false;
  
  for (int i = 0;  prefixes[i];  i++) {
    const size_t length = strlen(prefixes[i]);
    if (strncmp(version, prefixes[i], length) == 0) {
      version += length;
      break;
    }
  }
    
/* PR #18 */
#ifdef _MSC_VER
  sscanf_s(glVersion, "%d.%d", &major, &minor);
#else
  sscanf(version, "%d.%d", &major, &minor);
#endif

  OGL_VERSION_MAJOR = major; 
  OGL_VERSION_MINOR = minor;
  OGL_VERSION_1_0 = (major == 1 && minor >= 0) || major > 1;
  OGL_VERSION_1_1 = (major == 1 && minor >= 1) || major > 1;
  OGL_VERSION_1_2 = (major == 1 && minor >= 2) || major > 1;
  OGL_VERSION_1_3 = (major == 1 && minor >= 3) || major > 1;
  OGL_VERSION_1_4 = (major == 1 && minor >= 4) || major > 1;
  OGL_VERSION_1_5 = (major == 1 && minor >= 5) || major > 1;
  OGL_VERSION_2_0 = (major == 2 && minor >= 0) || major > 2;
  OGL_VERSION_2_1 = (major == 2 && minor >= 1) || major > 2;
  OGL_VERSION_3_0 = (major == 3 && minor >= 0) || major > 3;
  OGL_VERSION_3_1 = (major == 3 && minor >= 1) || major > 3;
  OGL_VERSION_3_2 = (major == 3 && minor >= 2) || major > 3;
  OGL_VERSION_3_3 = (major == 3 && minor >= 3) || major > 3;
  OGL_VERSION_4_0 = (major == 4 && minor >= 0) || major > 4;
  OGL_VERSION_4_1 = (major == 4 && minor >= 1) || major > 4;
  OGL_VERSION_4_2 = (major == 4 && minor >= 2) || major > 4;
  OGL_VERSION_4_3 = (major == 4 && minor >= 3) || major > 4;
  OGL_VERSION_4_4 = (major == 4 && minor >= 4) || major > 4;
  OGL_VERSION_4_5 = (major == 4 && minor >= 5) || major > 4;
  OGL_VERSION_4_6 = (major == 4 && minor >= 6) || major > 4;
  
  if (major > 4 || (major >= 4 && minor >= 6)) {
    major = OGL_VERSION_MAJOR = 4;
    minor = OGL_VERSION_MINOR = 6;
  }
  
  return true;
}
  
bool glLoad() {
  // check glVersion
  int maj,min;
  glVersion(maj,min);
  // load functions
  load_v_1_0();
  load_v_1_1();
  load_v_1_2();
  load_v_1_3();
  load_v_1_4();
  load_v_1_5();
  load_v_2_0();
  load_v_2_1();
  load_v_3_0();
  load_v_3_1();
  load_v_3_2();
  load_v_3_3();
  load_v_4_0();
  load_v_4_1();
  load_v_4_2();
  load_v_4_3();
  load_v_4_4();
  load_v_4_5();
  load_v_4_6();
  // load extensions
  load_exts();
  // return status
  return true;
}

